from ndsl.constants import X_DIM, Y_DIM, Z_DIM, Z_INTERFACE_DIM


class Temporaries:
    def __init__(self, quantity_factory):
        self.t1 = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.dp1 = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.omq = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.qv0 = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.ql0 = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.qr0 = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.qi0 = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.qs0 = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.qg0 = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.qa0 = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.qv1 = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.ql1 = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.qr1 = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.qi1 = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.qs1 = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.qg1 = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.qa1 = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.dz1 = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.den = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.den1 = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.denfac = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.p_dry = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.m1 = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.u1 = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.v1 = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.w1 = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.onemsig = quantity_factory.zeros([X_DIM, Y_DIM], "n/a")
        self.ccn = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.c_praut = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.rh_limited = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.ze = quantity_factory.zeros([X_DIM, Y_DIM, Z_INTERFACE_DIM], "n/a")
        self.zt = quantity_factory.zeros([X_DIM, Y_DIM, Z_INTERFACE_DIM], "n/a")
        self.lhi = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.icpk = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.hold_data = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.vti = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.vts = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.vtg = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.vtr = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.m1_sol = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.m1_rain = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.rain1 = quantity_factory.zeros([X_DIM, Y_DIM], "n/a")
        self.graupel1 = quantity_factory.zeros([X_DIM, Y_DIM], "n/a")
        self.snow1 = quantity_factory.zeros([X_DIM, Y_DIM], "n/a")
        self.ice1 = quantity_factory.zeros([X_DIM, Y_DIM], "n/a")
        self.evap1 = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
        self.subl1 = quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
