#!/bin/bash

if [ $# -lt 1 ]; then
        echo "no f90 specified"
        exit
fi

string=$1
array=(${string//./ })  

FILENAME=${array[0]}


NETCDF_PATH=/discover/nobackup/yzeng3/apps/netcdf-4.2.1.1

ifort -qopenmp ncdioMod.f90 rwncMod.f90 ${FILENAME}.f90 -I$NETCDF_PATH/include -L$NETCDF_PATH/lib -L/usr/local/intel/oneapi/2021/compiler/2021.4.0/linux/lib -lnetcdf -lnetcdff -o ${FILENAME}.out



