default_language_version:
  python: python3

files: pyMoist

repos:
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black
      additional_dependencies: ["click==8.0.4"]

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.4.2
    hooks:
    - id: isort
      args: ["--profile", "black"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
    - id: mypy
      name: mypy-pyMoist
      args: [
        --ignore-missing-imports,
        "--follow-imports=normal",
        --namespace-packages,
        --no-strict-optional,
        --warn-unreachable,
        --explicit-package-bases,
      ]
      additional_dependencies: [types-PyYAML]
      files: pyMoist

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-toml
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      name: flake8
      language_version: python3
      args: [
        "--exclude=docs",
        "--ignore=W503,E302,E203,F841",
        "--max-line-length=88"
      ]
      exclude: |
        (?x)^(
        .*/__init__.py |
        )$
    - id: flake8
      name: flake8 __init__.py files
      files: "__init__.py"
      # ignore unused import error in __init__.py files
      args: [
        "--exclude=docs",
        "--ignore=W503,E302,E203,F841,F401",
        "--max-line-length=100",]
