from dataclasses import dataclass

from ndsl.dsl.typing import Float, Int


@dataclass
class GF2020CumulusParameterizationConfig:
    DOWNDRAFT_MAX_HEIGHT_LAND_SHALLOW: Float
    DOWNDRAFT_MAX_HEIGHT_LAND_MID: Float
    DOWNDRAFT_MAX_HEIGHT_LAND_DEEP: Float
    DOWNDRAFT_MAX_HEIGHT_OCEAN_SHALLOW: Float
    DOWNDRAFT_MAX_HEIGHT_OCEAN_MID: Float
    DOWNDRAFT_MAX_HEIGHT_OCEAN_DEEP: Float
    UPDRAFT_MAX_HEIGHT_LAND_SHALLOW: Float
    UPDRAFT_MAX_HEIGHT_LAND_MID: Float
    UPDRAFT_MAX_HEIGHT_LAND_DEEP: Float
    UPDRAFT_MAX_HEIGHT_OCEAN_SHALLOW: Float
    UPDRAFT_MAX_HEIGHT_OCEAN_MID: Float
    UPDRAFT_MAX_HEIGHT_OCEAN_DEEP: Float
    MINIMUM_EVAP_FRACTION_LAND_SHALLOW: Float
    MINIMUM_EVAP_FRACTION_LAND_MID: Float
    MINIMUM_EVAP_FRACTION_LAND_DEEP: Float
    MINIMUM_EVAP_FRACTION_OCEAN_SHALLOW: Float
    MINIMUM_EVAP_FRACTION_OCEAN_MID: Float
    MINIMUM_EVAP_FRACTION_OCEAN_DEEP: Float
    MAXIMUM_EVAP_FRACTION_LAND_SHALLOW: Float
    MAXIMUM_EVAP_FRACTION_LAND_MID: Float
    MAXIMUM_EVAP_FRACTION_LAND_DEEP: Float
    MAXIMUM_EVAP_FRACTION_OCEAN_SHALLOW: Float
    MAXIMUM_EVAP_FRACTION_OCEAN_MID: Float
    MAXIMUM_EVAP_FRACTION_OCEAN_DEEP: Float
    CLOUD_BASE_MASS_FLUX_FACTOR_SHALLOW: Float
    CLOUD_BASE_MASS_FLUX_FACTOR_MID: Float
    CLOUD_BASE_MASS_FLUX_FACTOR_DEEP: Float
    USE_EXCESS_SHALLOW: Int
    USE_EXCESS_MID: Int
    USE_EXCESS_DEEP: Int
    ENABLE_SHALLOW: Float
    ENABLE_MID: Float
    ENABLE_DEEP: Float
    PLUME_ORDER: Float
