'''
Original Fortran file from 'src/Shared/@MAPL/shared/Constants/Constants.F90'
This is a port so NDSL has constants for math
'''

# Import math constants
import math_constants as mc

#Define whether or not to use CODATA 2018 constants
CODATA_2018_CONSTANTS = True

# Universal Constants
if CODATA_2018_CONSTANTS:
    MAPL_STFBOL = 5.670374419E-8  # W/(m^2 K^4)
    MAPL_AVOGAD = 6.02214076E26   # 1/kmol
    MAPL_RUNIV = 8314.462618      # J/(Kmole K)
else: 
    MAPL_STFBOL = 5.6734E-8  # W/(m^2 K^4)
    MAPL_AVOGAD = 6.023E26   # 1/kmol
    MAPL_RUNIV = 8314.47    # J/(Kmole K)

# Earth Constants
MAPL_PSDRY = 98305.0  # Pa
MAPL_SECONDS_PER_SIDEREAL_DAY = 86164.0  # s
MAPL_GRAV = 9.80665  # m^2/s
MAPL_RADIUS = 6371.0E3  # m
MAPL_OMEGA_R8 = 2.0 * mc.MAPL_PI_R8 / MAPL_SECONDS_PER_SIDEREAL_DAY  # 1/s
MAPL_OMEGA = 2.0 * mc.MAPL_PI / MAPL_SECONDS_PER_SIDEREAL_DAY  # 1/s
MAPL_EARTH_ECCENTRICITY = 8.181919084262200e-2  # --
MAPL_EARTH_SEMIMAJOR_AXIS = 6378137.0  # m
MAPL_KM_PER_DEG = (1.0 / (MAPL_RADIUS / 1000.0)) * mc.MAPL_RADIANS_TO_DEGREES
MAPL_DEG_PER_KM = (MAPL_RADIUS / 1000.0) * mc.MAPL_DEGREES_TO_RADIANS_R8

# Physical properties
MAPL_H2OMW = 18.015  # kg/Kmole
MAPL_O3MW = 47.9982  # kg/Kmole
MAPL_LATENT_HEAT_VAPORIZATION = 2.4665E6  # J/kg @15C @1atm
MAPL_ALHL = MAPL_LATENT_HEAT_VAPORIZATION  # J/kg
MAPL_LATENT_HEAT_FUSION = 3.3370E5  # J/kg @1atm
MAPL_ALHF = MAPL_LATENT_HEAT_FUSION  # J/kg
MAPL_LATENT_HEAT_SUBLIMATION = MAPL_ALHL + MAPL_ALHF  # J/kg
MAPL_ALHS = MAPL_LATENT_HEAT_SUBLIMATION  # J/kg

# Earth Specific Chemistry and Thermodynamic Constants
MAPL_AIRMW = 28.965  # kg/Kmole
MAPL_RDRY = MAPL_RUNIV / MAPL_AIRMW  # J/(kg K)
MAPL_CPDRY = 3.5 * MAPL_RDRY  # J/(kg K)
MAPL_CVDRY = MAPL_CPDRY - MAPL_RDRY  # J/(kg K)
MAPL_RVAP = MAPL_RUNIV / MAPL_H2OMW  # J/(kg K)
MAPL_CPVAP = 4.0 * MAPL_RVAP  # J/(kg K)
MAPL_CVVAP = MAPL_CPVAP - MAPL_RVAP  # J/(kg K)
MAPL_KAPPA = MAPL_RDRY / MAPL_CPDRY  # (2.0/7.0)
MAPL_EPSILON = MAPL_H2OMW / MAPL_AIRMW  # --
MAPL_DELTAP = MAPL_CPVAP / MAPL_CPDRY  # --
MAPL_DELTAV = MAPL_CVVAP / MAPL_CVDRY  # --
MAPL_GAMMAD = MAPL_CPDRY / MAPL_CVDRY  # --
MAPL_RGAS = MAPL_RDRY  # J/(kg K) (DEPRECATED)
MAPL_CP = MAPL_RGAS / MAPL_KAPPA  # J/(kg K) (DEPRECATED)
MAPL_VIREPS = 1.0 / MAPL_EPSILON - 1.0  # (DEPRECATED)
MAPL_P00 = 100000.0  # Pa
MAPL_CAPICE = 2000.0  # J/(K kg)
MAPL_CAPWTR = 4218.0  # J/(K kg)
MAPL_RHOWTR = 1000.0  # kg/m^3
MAPL_NUAIR = 1.533E-5  # m^2/S (@ 18C)
MAPL_TICE = 273.16  # K
MAPL_SRFPRS = 98470  # Pa
MAPL_KARMAN = 0.40  # --
MAPL_USMIN = 1.00  # m/s
MAPL_RHO_SEAWATER = 1026.0  # sea water density [kg/m^3]
MAPL_RHO_SEAICE = 917.0  # sea ice density [kg/m^3]
MAPL_RHO_SNOW = 330.0  # snow density [kg/m^3]
MAPL_CELSIUS_TO_KELVIN = 273.15  # K