from ndsl import QuantityFactory, StencilFactory, orchestrate
from ndsl.constants import X_DIM, Y_DIM, Z_DIM
from pyMoist.GFDL_1M.driver.config import config
from pyMoist.GFDL_1M.driver.finish.stencils import update_tendencies
from pyMoist.GFDL_1M.driver.support import ConfigConstants


class Finish:

    def __init__(
        self,
        stencil_factory: StencilFactory,
        quantity_factory: QuantityFactory,
        GFDL_1M_config: config,
        config_dependent_constants: ConfigConstants,
    ):

        # Initalize stencils
        orchestrate(obj=self, config=stencil_factory.config.dace_config)

        self._update_tendencies = stencil_factory.from_dims_halo(
            func=update_tendencies,
            compute_dims=[X_DIM, Y_DIM, Z_DIM],
            externals={
                "c_air": config_dependent_constants.C_AIR,
                "c_vap": config_dependent_constants.C_VAP,
                "rdt": config_dependent_constants.RDT,
                "do_sedi_w": GFDL_1M_config.DO_SEDI_W,
                "sedi_transport": GFDL_1M_config.SEDI_TRANSPORT,
                "do_qa": GFDL_1M_config.DO_QA,
            },
        )

    def __call__(
        self,
        qv0,
        ql0,
        qr0,
        qi0,
        qs0,
        qg0,
        qa0,
        qv1,
        ql1,
        qr1,
        qi1,
        qs1,
        qg1,
        qa1,
        ccn,
        qv_dt,
        ql_dt,
        qr_dt,
        qi_dt,
        qs_dt,
        qg_dt,
        qa_dt,
        t,
        t1,
        t_dt,
        w,
        w1,
        uin,
        u1,
        udt,
        vin,
        v1,
        vdt,
        dz,
        dp,
        dp1,
        den,
        p_dry,
        area,
        dt_moist,
        fr_land,
        cnv_frc,
        srf_type,
        eis,
        rh_limited,
        m1,
        anv_icefall,
        ls_icefall,
        revap,
        isubl,
        rain,
        snow,
        ice,
        graupel,
        m2_rain,
        m2_sol,
    ):
        self._update_tendencies(
            qv0,
            ql0,
            qr0,
            qi0,
            qs0,
            qg0,
            qa0,
            qv1,
            ql1,
            qr1,
            qi1,
            qs1,
            qg1,
            qa1,
            ccn,
            qv_dt,
            ql_dt,
            qr_dt,
            qi_dt,
            qs_dt,
            qg_dt,
            qa_dt,
            t,
            t1,
            t_dt,
            w,
            w1,
            uin,
            u1,
            udt,
            vin,
            v1,
            vdt,
            dz,
            dp,
            dp1,
            den,
            p_dry,
            area,
            dt_moist,
            fr_land,
            cnv_frc,
            srf_type,
            eis,
            rh_limited,
            m1,
            anv_icefall,
            ls_icefall,
            revap,
            isubl,
            rain,
            snow,
            ice,
            graupel,
            m2_rain,
            m2_sol,
        )
