from .GFDL_1M.driver.translate_GFDL_1M_driver import TranslateGFDL_1M_driver
from .GFDL_1M.driver.translate_GFDL_1M_driver_finish import (
    TranslateGFDL_1M_driver_finish,
)
from .GFDL_1M.driver.translate_GFDL_1M_driver_setup import TranslateGFDL_1M_driver_setup
from .GFDL_1M.driver.translate_GFDL_1M_fall_speed import TranslateGFDL_1M_fall_speed
from .GFDL_1M.driver.translate_GFDL_1M_ice_cloud import TranslateGFDL_1M_ice_cloud
from .GFDL_1M.driver.translate_GFDL_1M_terminal_fall import (
    TranslateGFDL_1M_terminal_fall,
)
from .GFDL_1M.driver.translate_GFDL_1M_warm_rain import TranslateGFDL_1M_warm_rain
from .GFDL_1M.driver.translate_GFDL_driver_tables import TranslateGFDL_driver_tables
from .GFDL_1M.PhaseChange.translate_GFDL_1M_bergeron_partition import (
    TranslateGFDL_1M_bergeron_partition,
)
from .GFDL_1M.PhaseChange.translate_GFDL_1M_evaporate import TranslateGFDL_1M_evaporate
from .GFDL_1M.PhaseChange.translate_GFDL_1M_hydrostatic_pdf import (
    TranslateGFDL_1M_hydrostatic_pdf,
)
from .GFDL_1M.PhaseChange.translate_GFDL_1M_melt_freeze import (
    TranslateGFDL_1M_melt_freeze,
)
from .GFDL_1M.PhaseChange.translate_GFDL_1M_phase_change import (
    TranslateGFDL_1M_phase_change,
)
from .GFDL_1M.PhaseChange.translate_GFDL_1M_sublimate import TranslateGFDL_1M_sublimate
from .GFDL_1M.translate_GFDL_1M_finalize import TranslateGFDL_1M_finalize
from .GFDL_1M.translate_GFDL_1M_radiation_coupling import (
    TranslateGFDL_1M_radiation_coupling,
)
from .GFDL_1M.translate_GFDL_1M_redistribute_clouds import (
    TranslateGFDL_1M_redistribute_clouds,
)
from .GFDL_1M.translate_GFDL_1M_setup import TranslateGFDL_1M_setup
from .saturation_tables.translate_qsat_functions import Translateqsat_functions
from .saturation_tables.translate_saturation_tables import Translatesaturation_tables
from .translate_aer_activation import TranslateAerActivation
from .translate_compute_uwshcu import TranslateComputeUwshcuInv


# GF_2020
# finalized tests
from .convection.GF_2020.cumulus_parameterization.translate_GF2020_CumulusParameterization import (
    TranslateGF2020_CumulusParameterization,
)

from .convection.GF_2020.cumulus_parameterization.setup.translate_GF2020_CumulusParameterization_Setup import (
    TranslateGF2020_CumulusParameterization_Setup_shallow,
    TranslateGF2020_CumulusParameterization_Setup_mid,
    TranslateGF2020_CumulusParameterization_Setup_deep,
)
from .convection.GF_2020.cumulus_parameterization.environment.translate_GF2020_Cumulus_Parameterization_EnvironmentConditions_1 import (
    TranslateGF2020_CumulusParameterization_EnvironmentConditions_1_shallow,
    TranslateGF2020_CumulusParameterization_EnvironmentConditions_1_mid,
    TranslateGF2020_CumulusParameterization_EnvironmentConditions_1_deep,
)
from .convection.GF_2020.cumulus_parameterization.environment.translate_GF2020_Cumulus_Parameterization_EnvironmentConditions_2 import (
    TranslateGF2020_CumulusParameterization_EnvironmentConditions_2_shallow,
    TranslateGF2020_CumulusParameterization_EnvironmentConditions_2_mid,
    TranslateGF2020_CumulusParameterization_EnvironmentConditions_2_deep,
)
from .convection.GF_2020.cumulus_parameterization.environment.translate_GF2020_Cumulus_Parameterization_EnvironmentCloudLevels_1 import (
    TranslateGF2020_CumulusParameterization_EnvironmentCloudLevels_1_shallow,
    TranslateGF2020_CumulusParameterization_EnvironmentCloudLevels_1_mid,
    TranslateGF2020_CumulusParameterization_EnvironmentCloudLevels_1_deep,
)
from .convection.GF_2020.cumulus_parameterization.environment.translate_GF2020_Cumulus_Parameterization_EnvironmentCloudLevels_2 import (
    TranslateGF2020_CumulusParameterization_EnvironmentCloudLevels_2_shallow,
    TranslateGF2020_CumulusParameterization_EnvironmentCloudLevels_2_mid,
    TranslateGF2020_CumulusParameterization_EnvironmentCloudLevels_2_deep,
)
from .convection.GF_2020.cumulus_parameterization.air_density.translate_GF2020_Cumulus_Parameterization_HydrostaticAirDensity import (
    TranslateGF2020_CumulusParameterization_HydrostaticAirDensity_shallow,
    TranslateGF2020_CumulusParameterization_HydrostaticAirDensity_mid,
    TranslateGF2020_CumulusParameterization_HydrostaticAirDensity_deep,
)
from .convection.GF_2020.cumulus_parameterization.precip.translate_GF2020_Cumulus_Parameterization_PartitionLiquidIceAndGetLevels import (
    TranslateGF2020_CumulusParameterization_PartitionLiquidIceAndGetLevels_shallow,
    TranslateGF2020_CumulusParameterization_PartitionLiquidIceAndGetLevels_mid,
    TranslateGF2020_CumulusParameterization_PartitionLiquidIceAndGetLevels_deep,
)
from .convection.GF_2020.cumulus_parameterization.get_levels.translate_GF2020_Cumulus_Parameterization_HighestMoistStaticEnergyLevel import (
    TranslateGF2020_CumulusParameterization_HighestMoistStaticEnergyLevel_shallow,
    TranslateGF2020_CumulusParameterization_HighestMoistStaticEnergyLevel_mid,
    TranslateGF2020_CumulusParameterization_HighestMoistStaticEnergyLevel_deep,
)
from .convection.GF_2020.cumulus_parameterization.get_levels.translate_GF2020_Cumulus_Parameterization_GetLCL import (
    TranslateGF2020_CumulusParameterization_GetLCL_shallow,
    TranslateGF2020_CumulusParameterization_GetLCL_mid,
    TranslateGF2020_CumulusParameterization_GetLCL_deep,
)
from .convection.GF_2020.cumulus_parameterization.moist_static_energy.translate_GF2020_Cumulus_Parameterization_ParcelMoistStaticEnergy_1 import (
    TranslateGF2020_CumulusParameterization_ParcelMoistStaticEnergy_1_shallow,
    TranslateGF2020_CumulusParameterization_ParcelMoistStaticEnergy_1_mid,
    TranslateGF2020_CumulusParameterization_ParcelMoistStaticEnergy_1_deep,
)
from .convection.GF_2020.cumulus_parameterization.entrainment.translate_GF2020_Cumulus_Parameterization_EntrainmentRates import (
    TranslateGF2020_CumulusParameterization_EntrainmentRates_shallow,
    TranslateGF2020_CumulusParameterization_EntrainmentRates_mid,
    TranslateGF2020_CumulusParameterization_EntrainmentRates_deep,
)
from .convection.GF_2020.cumulus_parameterization.get_levels.translate_GF2020_Cumulus_Parameterization_ConvectiveCloudBaseLevel import (
    TranslateGF2020_CumulusParameterization_ConvectiveCloudBaseLevel_shallow,
    TranslateGF2020_CumulusParameterization_ConvectiveCloudBaseLevel_mid,
    TranslateGF2020_CumulusParameterization_ConvectiveCloudBaseLevel_deep,
)
from .convection.GF_2020.cumulus_parameterization.entrainment.translate_GF2020_Cumulus_Parameterization_DowndraftEntrainmentProfiles import (
    TranslateGF2020_CumulusParameterization_DowndraftEntrainmentProfiles_shallow,
    TranslateGF2020_CumulusParameterization_DowndraftEntrainmentProfiles_mid,
    TranslateGF2020_CumulusParameterization_DowndraftEntrainmentProfiles_deep,
)
from .convection.GF_2020.cumulus_parameterization.moist_static_energy.translate_GF2020_Cumulus_Parameterization_ParcelMoistStaticEnergy_2 import (
    TranslateGF2020_CumulusParameterization_ParcelMoistStaticEnergy_2_shallow,
    TranslateGF2020_CumulusParameterization_ParcelMoistStaticEnergy_2_mid,
    TranslateGF2020_CumulusParameterization_ParcelMoistStaticEnergy_2_deep,
)
from .convection.GF_2020.cumulus_parameterization.entrainment.translate_GF2020_Cumulus_Parameterization_StableDetrainment import (
    TranslateGF2020_CumulusParameterization_StableDetrainment_shallow,
    TranslateGF2020_CumulusParameterization_StableDetrainment_mid,
    TranslateGF2020_CumulusParameterization_StableDetrainment_deep,
)
from .convection.GF_2020.cumulus_parameterization.get_levels.translate_GF2020_Cumulus_Parameterization_CloudTop import (
    TranslateGF2020_CumulusParameterization_CloudTop_shallow,
    TranslateGF2020_CumulusParameterization_CloudTop_mid,
    TranslateGF2020_CumulusParameterization_CloudTop_deep,
)
from .convection.GF_2020.cumulus_parameterization.updraft.translate_GF2020_Cumulus_Parameterization_UpdraftMassFlux import (
    TranslateGF2020_CumulusParameterization_UpdraftMassFlux_shallow,
    TranslateGF2020_CumulusParameterization_UpdraftMassFlux_mid,
    TranslateGF2020_CumulusParameterization_UpdraftMassFlux_deep,
)
from .convection.GF_2020.cumulus_parameterization.entrainment.translate_GF2020_Cumulus_Parameterization_CalculateMassEntrainmentDetrainment import (
    TranslateGF2020_CumulusParameterization_CalculateMassEntrainmentDetrainment_shallow,
    TranslateGF2020_CumulusParameterization_CalculateMassEntrainmentDetrainment_mid,
    TranslateGF2020_CumulusParameterization_CalculateMassEntrainmentDetrainment_deep,
)
from .convection.GF_2020.cumulus_parameterization.moist_static_energy.translate_GF2020_Cumulus_Parameterization_FirstGuessMoistStaticEnergy import (
    TranslateGF2020_CumulusParameterization_FirstGuessMoistStaticEnergy_shallow,
    TranslateGF2020_CumulusParameterization_FirstGuessMoistStaticEnergy_mid,
    TranslateGF2020_CumulusParameterization_FirstGuessMoistStaticEnergy_deep,
)
from .convection.GF_2020.cumulus_parameterization.buoyancy.translate_GF2020_Cumulus_Parameterization_GetBuoyancy_1 import (
    TranslateGF2020_CumulusParameterization_GetBuoyancy_1_shallow,
    TranslateGF2020_CumulusParameterization_GetBuoyancy_1_mid,
    TranslateGF2020_CumulusParameterization_GetBuoyancy_1_deep,
)
from .convection.GF_2020.cumulus_parameterization.profiles.translate_GF2020_CumulusParameterization_C1DProfile import (
    TranslateGF2020_CumulusParameterization_C1DProfile_shallow,
    TranslateGF2020_CumulusParameterization_C1DProfile_mid,
    TranslateGF2020_CumulusParameterization_C1DProfile_deep,
)
from .convection.GF_2020.cumulus_parameterization.updraft.translate_GF2020_Cumulus_Parameterization_UpdraftMoisture import (
    TranslateGF2020_CumulusParameterization_UpdraftMoisture_shallow,
    TranslateGF2020_CumulusParameterization_UpdraftMoisture_mid,
    TranslateGF2020_CumulusParameterization_UpdraftMoisture_deep,
)

from .convection.GF_2020.cumulus_parameterization.profiles.translate_GF2020_Cumulus_Parameterization_MeltingProfile import (
    TranslateGF2020_CumulusParameterization_MeltingProfile_shallow,
    TranslateGF2020_CumulusParameterization_MeltingProfile_mid,
    TranslateGF2020_CumulusParameterization_MeltingProfile_deep,
)
from .convection.GF_2020.cumulus_parameterization.updraft.translate_GF2020_Cumulus_Parameterization_UpdraftMoistStaticEnergyAndMomentumBudget import (
    TranslateGF2020_CumulusParameterization_UpdraftMoistStaticEnergyAndMomentumBudget_shallow,
    TranslateGF2020_CumulusParameterization_UpdraftMoistStaticEnergyAndMomentumBudget_mid,
    TranslateGF2020_CumulusParameterization_UpdraftMoistStaticEnergyAndMomentumBudget_deep,
)
from .convection.GF_2020.cumulus_parameterization.buoyancy.translate_GF2020_Cumulus_Parameterization_GetBuoyancy_2 import (
    TranslateGF2020_CumulusParameterization_GetBuoyancy_2_shallow,
    TranslateGF2020_CumulusParameterization_GetBuoyancy_2_mid,
    TranslateGF2020_CumulusParameterization_GetBuoyancy_2_deep,
)

from .convection.GF_2020.cumulus_parameterization.buoyancy.translate_GF2020_Cumulus_Parameterization_GetBuoyancy_3 import (
    TranslateGF2020_CumulusParameterization_GetBuoyancy_3_shallow,
    TranslateGF2020_CumulusParameterization_GetBuoyancy_3_mid,
    TranslateGF2020_CumulusParameterization_GetBuoyancy_3_deep,
)
from .convection.GF_2020.cumulus_parameterization.updraft.translate_GF2020_Cumulus_Parameterization_UpdraftInitialWorkfunctions import (
    TranslateGF2020_CumulusParameterization_UpdraftInitialWorkfunctions_deep,
    TranslateGF2020_CumulusParameterization_UpdraftInitialWorkfunctions_mid,
    TranslateGF2020_CumulusParameterization_UpdraftInitialWorkfunctions_shallow,
)
from .convection.GF_2020.cumulus_parameterization.updraft.translate_GF2020_Cumulus_Parameterization_UpdraftTemperature import (
    TranslateGF2020_CumulusParameterization_UpdraftTemperature_deep,
    TranslateGF2020_CumulusParameterization_UpdraftTemperature_mid,
    TranslateGF2020_CumulusParameterization_UpdraftTemperature_shallow,
)
from .convection.GF_2020.cumulus_parameterization.updraft.translate_GF2020_Cumulus_Parameterization_UpdraftVerticalVelocity import (
    TranslateGF2020_CumulusParameterization_UpdraftVerticalVelocity_deep,
    TranslateGF2020_CumulusParameterization_UpdraftVerticalVelocity_mid,
    TranslateGF2020_CumulusParameterization_UpdraftVerticalVelocity_shallow,
)
from .convection.GF_2020.cumulus_parameterization.downdraft.translate_GF2020_Cumulus_Parameterization_DowndraftOriginLevel import (
    TranslateGF2020_CumulusParameterization_DowndraftOriginLevel_deep,
    TranslateGF2020_CumulusParameterization_DowndraftOriginLevel_mid,
    TranslateGF2020_CumulusParameterization_DowndraftOriginLevel_shallow,
)
from .convection.GF_2020.cumulus_parameterization.downdraft.translate_GF2020_Cumulus_Parameterization_DowndraftLateralMassFlux import (
    TranslateGF2020_CumulusParameterization_DowndraftLateralMassFlux_deep,
    TranslateGF2020_CumulusParameterization_DowndraftLateralMassFlux_mid,
    TranslateGF2020_CumulusParameterization_DowndraftLateralMassFlux_shallow,
)

# NOTE need to organize everything below here
from .convection.GF_2020.cumulus_parameterization.updraft.translate_GF2020_Cumulus_Parameterization_UpdraftCIN import (
    TranslateGF2020_CumulusParameterization_UpdraftCIN_deep,
    TranslateGF2020_CumulusParameterization_UpdraftCIN_mid,
    TranslateGF2020_CumulusParameterization_UpdraftCIN_shallow,
)

from .convection.GF_2020.cumulus_parameterization.trigger_function.translate_GF2020_Cumulus_Parameterization_TriggerFunctionConvection import (
    TranslateGF2020_CumulusParameterization_TriggerFunctionConvection_deep,
    TranslateGF2020_CumulusParameterization_TriggerFunctionConvection_mid,
    TranslateGF2020_CumulusParameterization_TriggerFunctionConvection_shallow,
)

from .convection.GF_2020.cumulus_parameterization.profiles.translate_GF2020_Cumulus_Parameterization_InCloudTemperature import (
    TranslateGF2020_CumulusParameterization_InCloudTemperature_deep,
    TranslateGF2020_CumulusParameterization_InCloudTemperature_mid,
    TranslateGF2020_CumulusParameterization_InCloudTemperature_shallow,
)

from .convection.GF_2020.cumulus_parameterization.diurnal_cycle.translate_GF2020_Cumulus_Parameterization_DiurnalCycle import (
    TranslateGF2020_CumulusParameterization_DiurnalCycle_deep,
    TranslateGF2020_CumulusParameterization_DiurnalCycle_mid,
    TranslateGF2020_CumulusParameterization_DiurnalCycle_shallow,
)

from .convection.GF_2020.cumulus_parameterization.downdraft.translate_GF2020_Cumulus_Parameterization_DowndraftWindshear import (
    TranslateGF2020_CumulusParameterization_DowndraftWindshear_deep,
    TranslateGF2020_CumulusParameterization_DowndraftWindshear_mid,
    TranslateGF2020_CumulusParameterization_DowndraftWindshear_shallow,
)

# in progress tests
from .convection.GF_2020.cumulus_parameterization.awaiting_permanant_home.translate_get_melting_profile import (
    TranslateGetMeltingProfile,
)
from .convection.GF_2020.awaiting_permanant_home.translate_GF2020_Setup import (
    TranslateGF2020_Setup,
)
from .convection.GF_2020.cumulus_parameterization.awaiting_permanant_home.translate_get_partition_liq_ice import (
    TranslateGetPartitionLiqIce,
)
from .convection.GF_2020.cumulus_parameterization.awaiting_permanant_home.translate_ke_to_heating import (
    TranslateKeToHeating,
)
from .convection.GF_2020.cumulus_parameterization.awaiting_permanant_home.translate_get_precip_fluxes import (
    TranslateGetPrecipFluxes,
)
from .convection.GF_2020.cumulus_parameterization.awaiting_permanant_home.translate_rates_up_pdf import (
    TranslateRatesUpPdf,
)
from .convection.GF_2020.cumulus_parameterization.awaiting_permanant_home.translate_ke_to_heating import (
    TranslateKeToHeating,
)
from .convection.GF_2020.cumulus_parameterization.awaiting_permanant_home.translate_get_precip_fluxes import (
    TranslateGetPrecipFluxes,
)
from .convection.GF_2020.cumulus_parameterization.awaiting_permanant_home.translate_rates_up_pdf import (
    TranslateRatesUpPdf,
)
from .convection.GF_2020.cumulus_parameterization.awaiting_permanant_home.translate_cup_dd_edt import (
    TranslateCupDDEdt,
)
from .convection.GF_2020.cumulus_parameterization.awaiting_permanant_home.translate_rain_evap_below_cloudbase import (
    TranslateRainEvapBelowCloudbase,
)
from .convection.GF_2020.cumulus_parameterization.awaiting_permanant_home.translate_cloud_dissipation import (
    TranslateCloudDissipation,
)
from .convection.GF_2020.cumulus_parameterization.awaiting_permanant_home.translate_cup_up_moisture import (
    TranslateCupUpMoisture,
)
from .convection.GF_2020.cumulus_parameterization.awaiting_permanant_home.translate_cup_up_aa0 import (
    TranslateCupUpAa0,
)
