from dataclasses import dataclass

from ndsl.dsl.typing import Float, Int


@dataclass
class GFDL1MConfig:
    PHYS_HYDROSTATIC: bool
    HYDROSTATIC: bool
    DT_MOIST: Float
    MP_TIME: Float
    T_MIN: Float
    T_SUB: Float
    TAU_R2G: Float
    TAU_SMLT: Float
    TAU_G2R: Float
    DW_LAND: Float
    DW_OCEAN: Float
    VI_FAC: Float
    VR_FAC: Float
    VS_FAC: Float
    VG_FAC: Float
    QL_MLT: Float
    DO_QA: bool
    FIX_NEGATIVE: bool
    VI_MAX: Float
    VS_MAX: Float
    VG_MAX: Float
    VR_MAX: Float
    QS_MLT: Float
    QS0_CRT: Float
    QI_GEN: Float
    QL0_MAX: Float
    QI0_MAX: Float
    QI0_CRT: Float
    QR0_CRT: Float
    FAST_SAT_ADJ: bool
    RH_INC: Float
    RH_INS: Float
    RH_INR: Float
    CONST_VI: bool
    CONST_VS: bool
    CONST_VG: bool
    CONST_VR: bool
    USE_CCN: bool
    RTHRESHU: Float
    RTHRESHS: Float
    CCN_L: Float
    CCN_O: Float
    QC_CRT: Float
    TAU_G2V: Float
    TAU_V2G: Float
    TAU_S2V: Float
    TAU_V2S: Float
    TAU_REVP: Float
    TAU_FRZ: Float
    DO_BIGG: bool
    DO_EVAP: bool
    DO_SUBL: bool
    SAT_ADJ0: Float
    C_PIACR: Float
    TAU_IMLT: Float
    TAU_V2L: Float
    TAU_L2V: Float
    TAU_I2V: Float
    TAU_I2S: Float
    TAU_L2R: Float
    QI_LIM: Float
    QL_GEN: Float
    C_PAUT: Float
    C_PSACI: Float
    C_PGACS: Float
    C_PGACI: Float
    Z_SLOPE_LIQ: bool
    Z_SLOPE_ICE: bool
    PROG_CCN: bool
    C_CRACW: Float
    ALIN: Float
    CLIN: Float
    PRECIPRAD: bool
    CLD_MIN: Float
    USE_PPM: bool
    MONO_PROF: bool
    DO_SEDI_HEAT: bool
    SEDI_TRANSPORT: bool
    DO_SEDI_W: bool
    DE_ICE: bool
    ICLOUD_F: Float
    IRAIN_F: Float
    MP_PRINT: bool
    MELTFRZ: bool
    USE_BERGERON: bool
    TURNRHCRIT_PARAM: Float
    PDF_SHAPE: Int
    ANV_ICEFALL: Float
    LS_ICEFALL: Float
    LIQ_RADII_PARAM: Int
    ICE_RADII_PARAM: Int
    FAC_RI: Float
    MIN_RI: Float
    MAX_RI: Float
    FAC_RL: Float
    MIN_RL: Float
    MAX_RL: Float
    CCW_EVAP_EFF: Float
    CCI_EVAP_EFF: Float
