name: NDSL Lint & Translate Tests

on:
  pull_request:
    paths:
      - '.github/workflows/ndsl-checks.yml'
      - 'GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/**'
  workflow_dispatch:

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    env:
      DATA_PATH: ./test_data/11.5.2/TBC_C24_L72/moist
      DATA_URL: "https://portal.nccs.nasa.gov/datashare/astg/smt/geos-fp/translate/11.5.2/x86_GNU/Moist/TBC_C24L72_20251208.tar.gz"
    runs-on: ubuntu-latest
    steps:
      - name: Step Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install MPI
        run: pip install mpich

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Python packages
        run: |
          cd GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist
          pip install .

      - name: Run lint via pre-commit
        run: |
          cd GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist
          pre-commit run --all-files --show-diff-on-failure

      - name: Build Documentation
        run: |
          cd GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist
          mkdocs build

      - name: Download test_data
        run: |
          cd GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist
          mkdir -p ${{ env.DATA_PATH }} && cd ${{ env.DATA_PATH }}
          wget --no-verbose ${{ env.DATA_URL }}
          tar -xzf TBC_C24L72_20251208.tar.gz
          # These don't have translate tests
          rm Constants.MAPL-In.nc
          rm Constants.ProcessLibrary-In.nc
          rm GF2020_CumulusParameterization_TriggerFunctionConvection-In.nc
          rm ComputeUwshcu-In.nc
          rm AerActivation-In.nc
          rm GF2020_CumulusParameterization_GetBuoyancy_1-In.nc
          rm GF2020_CumulusParameterization_UpdraftCIN-In.nc
          rm GF2020_CumulusParameterization_InCloudTemperature-In.nc
          rm GF2020_CumulusParameterization_EnvironmentCloudLevels_1-In.nc
          rm GF2020_CumulusParameterization_UpdraftInitialWorkfunctions-In.nc
          rm GF2020_CumulusParameterization_MeltingProfile-In.nc

      - name: Run regular unit tests
        env:
          EXP_NAME: 'gcm-fp'
        run : |
          cd GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist
          pytest ./tests/numerical
          
      - name: Run translate tests
        env:
          EXP_NAME: 'gcm-fp'
        run: |
          cd GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/tests/scripts/
          ./run_all.sh ../../${{ env.DATA_PATH }} st:dace:cpu:KIJ
