name: Build Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    # Do not run if the only files changed cannot affect the build
    paths-ignore:
      - "**.md"
      - "**.pro"
      - "**.sh"
      - "**.perl"
      - ".github/CODEOWNERS"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build_gcm:
    strategy:
      matrix:
        compiler: [ifort, ifx, gfortran-14, gfortran-15]
        build-type: [Debug]
    uses: GEOS-ESM/CI-workflows/.github/workflows/geosgcm_build_tests.yml@project/geosgcm
    with:
      compiler: ${{ matrix.compiler }}
      cmake-build-type: ${{ matrix.build-type }}
